spring:
  kafka:
    consumer:
      bootstrap-servers: psawesome.xyz:50900
      group-id: cheese-webserver-group
      client-id: cheese-webserver
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: http://psawesome.xyz:59292
