management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true

logging:
  level:
    sql: info
#    org.springframework: debug
    org.springframework.data.mongodb.repository: debug
    level:
      com:
        mongodb:
          reactivestreams: debug
      org:
        springframework:
          data:
            mongodb:  debug

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
  elasticsearch:
    uris: psawesome.xyz:59292


  kafka:
    consumer:
      client-id: cheese-webserver-dev
      bootstrap-servers: psawesome.xyz:50900
      auto-offset-reset: latest
      group-id: cheese-web-db-sync-group
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true

    properties:
      hibernate:
        ogm:
          datastore:
            create_database: true

    allow-circular-references: true

reactor:
  netty:
    http:
      server:
        accessLogEnabled: true
server:
  http2:
    enabled: true


