spring:
  kafka:
    consumer:
      bootstrap-servers: psawesome.xyz:50900
      group-id: cheese-webserver-group
      client-id: cheese-webserver
  data:
    mongodb:
      username: admin
      password: powerful090
      authentication-database: admin
      host: localhost
      port: 27017
#      uri: mongodb://admin:powerful090@psawesome.xyz:57017/cheese-five
      repositories:
        type: reactive
      uuid-representation: standard
      database: cheese_five

elasticsearch:
  host: psawesome.xyz
  port: 59292

cheese-mongo:
  driver-name: nodejs|mongosh
  driver-platform: Node.js v16.19.0, LE (unified)
  driver-version: 4.13.0