management:
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true

logging:
  level:
    org.springframework: info
    org:
      elasticsearch:
        client: trace

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017
      host: psawesome.xyz
      port: 57017
      database: cheese_five
  kafka:
    consumer:
      client-id: cheese-webserver-dev
      bootstrap-servers: psawesome.xyz:50900
      auto-offset-reset: latest
      group-id: cheese-web-db-sync-group
  jpa:
    show-sql: true
  main:
    allow-bean-definition-overriding: true

    properties:
      hibernate:
        ogm:
          datastore:
            create_database: true
reactor:
  netty:
    http:
      server:
        accessLogEnabled: true

elasticsearch:
  host: psawesome.xyz
  port: 59292

cheese-mongo:
  driver-name: mongo-java-driver|reactive-streams|spring-data
  driver-platform: Java/Azul Systems, Inc./17.0.5+8-LTS
  driver-version: 4.8.1
