import java.text.SimpleDateFormat

node {

	parameters {
		string(name: 'BRANCH', defaultValue: 'develop', description: '')
	}

	stage('Src Checkout') {
		git branch: '${BRANCH}',
			credentialsId: '3641a3eb-48a3-4c6e-8dd8-6d77ff718525',
			url: 'https://github.com/wiv33/cheese.git'
	}

  	stage('Build') {
  		sh './gradlew bootJar'
  	}

  	stage('Docker build') {
	  	image = docker.build('psawesome/xyz-cheese-web:${BUILD_NUMBER}')
  	}

  	stage('Docker push') {
		docker.withRegistry('https://registry.hub.docker.com', dockerHubCred){
                        appImage.push("${env.BUILD_NUMBER}")
                        appImage.push("latest")
                    }
  	}
}